<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CalendarApp Signin</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/sticky-footer-navbar/sticky-footer-navbar.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- set the background color and box shadow for the sign in div -->
    <style type="text/css">
    	.signin_container {
    		background-color: white;
    		padding: 20px;
    		box-shadow: 10px 10px 5px #888888;
    	}
    </style>

  </head>

  <body>

    <div class="container">
		<?php $this->print_view(); ?>
    </div> <!-- /container -->

    <div class="footer">
        <div class="container">
            <p class="text-muted" style="text-align: center">This page was developed by <a href="mailto:<?php echo ADMIN_EMAIL; ?>" style='color: black'><?php echo ADMIN_NAME; ?></a></p>
        </div>
    </div>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
